[2024-04-28 13:53:50,748: INFO: main: >>>>>> Starting pipeline <<<<<<]
[2024-04-28 15:34:14,791: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 15:34:15,012: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 15:34:15,030: INFO: common: created directory at: artifacts]
[2024-04-28 15:34:15,049: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-28 15:34:15,050: INFO: 3172177572: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-28 15:34:18,776: INFO: 3172177572: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-28 15:50:16,349: INFO: main: >>>>>> Starting pipeline <<<<<<]
[2024-04-28 15:50:16,349: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-28 15:50:16,350: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 15:50:16,351: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 15:50:16,351: INFO: common: created directory at: artifacts]
[2024-04-28 15:50:16,351: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-28 15:50:16,351: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-28 15:50:20,824: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-28 15:50:24,745: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-28 16:59:07,632: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 16:59:07,855: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 16:59:07,857: INFO: common: created directory at: artifacts]
[2024-04-28 16:59:07,878: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-28 16:59:11,214: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-28 17:18:43,827: INFO: main: >>>>>> Starting pipeline <<<<<<]
[2024-04-28 17:18:43,839: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-28 17:18:43,840: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 17:18:43,842: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 17:18:43,842: INFO: common: created directory at: artifacts]
[2024-04-28 17:18:43,842: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-28 17:18:43,843: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-28 17:18:48,841: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-28 17:18:52,667: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-28 17:18:52,667: INFO: main: *******************]
[2024-04-28 17:18:52,668: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-28 17:18:52,669: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 17:18:52,670: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 17:18:52,671: INFO: common: created directory at: artifacts]
[2024-04-28 17:18:52,671: ERROR: main: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config']
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    prepare_base_model.main()
  File "e:\hajni\github\kidney_disease_classification\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
AttributeError: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config'
[2024-04-28 17:19:50,614: INFO: main: >>>>>> Starting pipeline <<<<<<]
[2024-04-28 17:19:50,627: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-28 17:19:50,628: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 17:19:50,630: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 17:19:50,631: INFO: common: created directory at: artifacts]
[2024-04-28 17:19:50,631: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-28 17:19:50,631: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-28 17:19:55,109: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-28 17:19:58,927: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-28 17:19:58,927: INFO: main: *******************]
[2024-04-28 17:19:58,927: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-28 17:19:58,930: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 17:19:58,932: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 17:19:58,933: INFO: common: created directory at: artifacts]
[2024-04-28 17:19:58,933: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-28 17:19:59,269: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-28 17:20:03,075: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-04-28 17:59:35,127: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 17:59:35,141: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 17:59:35,142: INFO: common: created directory at: artifacts]
[2024-04-28 17:59:35,165: INFO: common: created directory at: artifacts\training]
[2024-04-28 19:08:51,642: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 19:08:51,866: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 19:08:51,867: INFO: common: created directory at: artifacts]
[2024-04-28 19:09:03,239: INFO: common: json file saved at: scores.json]
[2024-04-28 19:09:05,648: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-28 19:09:06,095: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmpp6__dsxq\model\data\model\assets]
[2024-04-28 19:28:25,648: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 19:28:25,871: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 19:28:25,872: INFO: common: created directory at: artifacts]
[2024-04-28 19:28:36,398: INFO: common: json file saved at: scores.json]
[2024-04-28 19:28:38,473: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-28 19:28:38,896: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmpz82rmp7z\model\data\model\assets]
[2024-04-28 19:31:30,343: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 19:31:30,357: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 19:31:30,358: INFO: common: created directory at: artifacts]
[2024-04-28 19:31:40,811: INFO: common: json file saved at: scores.json]
[2024-04-28 19:31:42,884: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-28 19:31:43,296: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmpa3708uff\model\data\model\assets]
[2024-04-28 19:34:54,505: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 19:34:54,520: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 19:34:54,521: INFO: common: created directory at: artifacts]
[2024-04-28 19:35:05,355: INFO: common: json file saved at: scores.json]
[2024-04-28 19:35:07,632: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-28 19:35:08,090: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmpr3wt7u43\model\data\model\assets]
[2024-04-28 19:40:11,126: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 19:40:11,141: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 19:40:11,142: INFO: common: created directory at: artifacts]
[2024-04-28 19:40:21,478: INFO: common: json file saved at: scores.json]
[2024-04-28 19:40:23,626: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-28 19:40:24,058: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmpz39n71_7\model\data\model\assets]
[2024-04-28 20:43:38,274: INFO: main: >>>>>> Starting pipeline <<<<<<]
[2024-04-28 20:43:38,286: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-28 20:43:38,288: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 20:43:38,289: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 20:43:38,289: INFO: common: created directory at: artifacts]
[2024-04-28 20:43:38,290: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-28 20:43:38,290: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-28 20:43:42,790: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-28 20:43:46,768: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-28 20:43:46,768: INFO: main: *******************]
[2024-04-28 20:43:46,768: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-28 20:43:46,769: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 20:43:46,770: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 20:43:46,771: INFO: common: created directory at: artifacts]
[2024-04-28 20:43:46,771: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-28 20:43:47,077: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-28 20:43:50,852: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-04-28 20:43:50,853: INFO: main: *******************]
[2024-04-28 20:43:50,853: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-04-28 20:43:50,854: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 20:43:50,855: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 20:43:50,856: INFO: common: created directory at: artifacts]
[2024-04-28 20:43:50,856: INFO: common: created directory at: artifacts\training]
[2024-04-28 20:44:24,111: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-04-28 20:44:24,111: INFO: main: *******************]
[2024-04-28 20:44:24,111: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-04-28 20:44:24,113: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 20:44:24,115: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 20:44:24,115: INFO: common: created directory at: artifacts]
[2024-04-28 20:44:34,175: INFO: common: json file saved at: scores.json]
[2024-04-28 20:44:34,183: INFO: common: json file saved at: scores.json]
[2024-04-28 20:44:36,304: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-28 20:44:36,752: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmpy2q67f67\model\data\model\assets]
[2024-04-28 20:44:56,580: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-04-28 20:47:57,713: INFO: main: >>>>>> Starting pipeline <<<<<<]
[2024-04-28 20:47:57,727: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-28 20:47:57,728: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 20:47:57,729: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 20:47:57,730: INFO: common: created directory at: artifacts]
[2024-04-28 20:47:57,730: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-28 20:47:57,730: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-28 20:48:02,141: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-28 20:48:06,063: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-28 20:48:06,063: INFO: main: *******************]
[2024-04-28 20:48:06,063: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-28 20:48:06,066: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 20:48:06,067: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 20:48:06,067: INFO: common: created directory at: artifacts]
[2024-04-28 20:48:06,068: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-28 20:48:06,393: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-28 20:48:10,192: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-04-28 20:48:10,192: INFO: main: *******************]
[2024-04-28 20:48:10,192: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-04-28 20:48:10,195: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 20:48:10,196: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 20:48:10,196: INFO: common: created directory at: artifacts]
[2024-04-28 20:48:10,197: INFO: common: created directory at: artifacts\training]
[2024-04-28 20:49:18,861: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-04-28 20:49:18,861: INFO: main: *******************]
[2024-04-28 20:49:18,861: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-04-28 20:49:18,864: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 20:49:18,866: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 20:49:18,866: INFO: common: created directory at: artifacts]
[2024-04-28 20:49:29,913: INFO: common: json file saved at: scores.json]
[2024-04-28 20:49:29,920: INFO: common: json file saved at: scores.json]
[2024-04-28 20:49:32,307: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-28 20:49:32,772: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmpehuu1b4r\model\data\model\assets]
[2024-04-28 20:49:53,093: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-04-28 20:51:33,369: INFO: main: >>>>>> Starting pipeline <<<<<<]
[2024-04-28 20:51:33,381: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-28 20:51:33,383: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 20:51:33,384: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 20:51:33,410: INFO: common: created directory at: artifacts]
[2024-04-28 20:51:33,435: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-28 20:51:33,436: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-28 20:51:37,647: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-28 20:51:41,336: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-28 20:51:41,337: INFO: main: *******************]
[2024-04-28 20:51:41,337: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-28 20:51:41,338: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 20:51:41,340: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 20:51:41,340: INFO: common: created directory at: artifacts]
[2024-04-28 20:51:41,360: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-28 20:51:41,665: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-28 20:51:45,412: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-04-28 20:51:45,412: INFO: main: *******************]
[2024-04-28 20:51:45,412: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-04-28 20:51:45,415: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 20:51:45,417: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 20:51:45,417: INFO: common: created directory at: artifacts]
[2024-04-28 20:51:45,438: INFO: common: created directory at: artifacts\training]
[2024-04-28 20:52:49,369: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-04-28 20:52:49,369: INFO: main: *******************]
[2024-04-28 20:52:49,369: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-04-28 20:52:49,371: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 20:52:49,373: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 20:52:49,373: INFO: common: created directory at: artifacts]
[2024-04-28 20:52:59,703: INFO: common: json file saved at: scores.json]
[2024-04-28 20:52:59,709: INFO: common: json file saved at: scores.json]
[2024-04-28 20:53:02,134: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-28 20:53:02,558: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmprwwc_5vu\model\data\model\assets]
[2024-04-28 20:53:22,485: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-04-28 21:18:01,429: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-28 21:18:01,431: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 21:18:01,433: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 21:18:01,450: INFO: common: created directory at: artifacts]
[2024-04-28 21:18:01,467: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-28 21:18:01,467: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-28 21:18:04,474: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-28 21:18:07,822: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-28 21:18:33,755: INFO: stage_02_prepare_base_model: *******************]
[2024-04-28 21:18:33,768: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-28 21:18:33,769: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 21:18:33,771: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 21:18:33,771: INFO: common: created directory at: artifacts]
[2024-04-28 21:18:33,788: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-28 21:18:34,121: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-28 21:18:37,487: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-04-28 21:18:48,225: INFO: stage_03_model_training: *******************]
[2024-04-28 21:18:48,240: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-04-28 21:18:48,241: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 21:18:48,243: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 21:18:48,243: INFO: common: created directory at: artifacts]
[2024-04-28 21:18:48,264: INFO: common: created directory at: artifacts\training]
[2024-04-28 21:19:52,503: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-04-28 21:20:00,474: INFO: stage_04_model_evaluation: *******************]
[2024-04-28 21:20:00,486: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-04-28 21:20:00,487: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-28 21:20:00,488: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-28 21:20:00,489: INFO: common: created directory at: artifacts]
[2024-04-28 21:20:10,824: INFO: common: json file saved at: scores.json]
[2024-04-28 21:20:10,830: INFO: common: json file saved at: scores.json]
[2024-04-28 21:20:10,830: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-04-28 21:43:50,156: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.70:8080]
[2024-04-28 21:43:50,169: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-04-28 21:44:08,829: INFO: _internal: 127.0.0.1 - - [28/Apr/2024 21:44:08] "GET / HTTP/1.1" 200 -]
[2024-04-28 21:44:41,769: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "e:\hajni\github\kidney_disease_classification\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-04-28 21:44:41,784: INFO: _internal: 127.0.0.1 - - [28/Apr/2024 21:44:41] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-04-28 21:45:46,562: INFO: _internal: 127.0.0.1 - - [28/Apr/2024 21:45:46] "GET / HTTP/1.1" 200 -]
[2024-04-28 21:46:30,197: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.70:8080]
[2024-04-28 21:46:30,209: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-04-28 21:46:33,975: INFO: _internal: 127.0.0.1 - - [28/Apr/2024 21:46:33] "GET / HTTP/1.1" 200 -]
[2024-04-28 21:46:45,552: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "e:\hajni\github\kidney_disease_classification\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("training", "model.h5"))
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at training\model.h5
[2024-04-28 21:46:45,555: INFO: _internal: 127.0.0.1 - - [28/Apr/2024 21:46:45] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-04-28 21:48:25,856: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.70:8080]
[2024-04-28 21:48:25,869: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-04-28 21:48:25,878: INFO: _internal: 127.0.0.1 - - [28/Apr/2024 21:48:25] "GET / HTTP/1.1" 200 -]
[2024-04-28 21:48:33,227: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "e:\hajni\github\kidney_disease_classification\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join( "model.h5"))
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model.h5
[2024-04-28 21:48:33,233: INFO: _internal: 127.0.0.1 - - [28/Apr/2024 21:48:33] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-04-28 21:49:18,019: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.70:8080]
[2024-04-28 21:49:18,032: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-04-28 21:49:18,184: INFO: _internal: 127.0.0.1 - - [28/Apr/2024 21:49:18] "GET / HTTP/1.1" 200 -]
[2024-04-28 21:49:19,048: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "e:\hajni\github\kidney_disease_classification\src\cnnClassifier\pipeline\prediction.py", line 19, in predict
    test_image = image.load_img(imagename, target_size = (224,224))
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\keras\utils\image_utils.py", line 423, in load_img
    img = pil_image.open(io.BytesIO(f.read()))
  File "C:\Users\User\miniconda3\envs\kidney\lib\site-packages\PIL\Image.py", line 3339, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x00000274C7DFF950>
[2024-04-28 21:49:19,052: INFO: _internal: 127.0.0.1 - - [28/Apr/2024 21:49:19] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-04-28 21:49:20,627: INFO: _internal: 127.0.0.1 - - [28/Apr/2024 21:49:20] "GET / HTTP/1.1" 200 -]
[2024-04-28 21:49:28,301: INFO: _internal: 127.0.0.1 - - [28/Apr/2024 21:49:28] "POST /predict HTTP/1.1" 200 -]
[2024-04-28 21:49:44,473: INFO: _internal: 127.0.0.1 - - [28/Apr/2024 21:49:44] "POST /predict HTTP/1.1" 200 -]
[2024-04-28 21:49:54,773: INFO: _internal: 127.0.0.1 - - [28/Apr/2024 21:49:54] "POST /predict HTTP/1.1" 200 -]
[2024-04-28 21:50:05,397: INFO: _internal: 127.0.0.1 - - [28/Apr/2024 21:50:05] "POST /predict HTTP/1.1" 200 -]
[2024-04-28 21:50:12,349: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000274C7C98160> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-04-28 21:50:12,354: INFO: _internal: 127.0.0.1 - - [28/Apr/2024 21:50:12] "POST /predict HTTP/1.1" 200 -]
[2024-04-28 21:50:21,810: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000274C7FE1790> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-04-28 21:50:21,814: INFO: _internal: 127.0.0.1 - - [28/Apr/2024 21:50:21] "POST /predict HTTP/1.1" 200 -]
[2024-04-28 21:50:30,765: INFO: _internal: 127.0.0.1 - - [28/Apr/2024 21:50:30] "POST /predict HTTP/1.1" 200 -]
